### ISSUE TITLE
Unable to run yg-acyclic.py

### ISSUE THREAD

**Issue by Tracachang** [JoinMarket-Org/custom-scripts#5]
Hello

Running Raspibolt (Raspberry pi4 with buster) I try to run yg-acyclic.py and I got this error:

```
(jmvenv) $ python yg-acyclic.py wallet.jmdat
Enter wallet decryption passphrase: 
Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/bitcoin/joinmarket-clientserver-0.6.0/jmvenv/lib/python3.7/site-packages/jmclient/yieldgenerator.py", line 33, in __init__
    Maker.__init__(self, wallet_service)
  File "/home/bitcoin/joinmarket-clientserver-0.6.0/jmvenv/lib/python3.7/site-packages/jmclient/maker.py", line 35, in __init__
    self.sync_wait_loop.start(2.0)
  File "/home/bitcoin/joinmarket-clientserver-0.6.0/jmvenv/lib/python3.7/site-packages/twisted/internet/task.py", line 194, in start
    self()
  File "/home/bitcoin/joinmarket-clientserver-0.6.0/jmvenv/lib/python3.7/site-packages/twisted/internet/task.py", line 239, in __call__
    d = defer.maybeDeferred(self.f, *self.a, **self.kw)
--- <exception caught here> ---
  File "/home/bitcoin/joinmarket-clientserver-0.6.0/jmvenv/lib/python3.7/site-packages/twisted/internet/defer.py", line 151, in maybeDeferred
    result = f(*args, **kw)
  File "/home/bitcoin/joinmarket-clientserver-0.6.0/jmvenv/lib/python3.7/site-packages/jmclient/maker.py", line 47, in try_to_create_my_orders
    self.offerlist = self.create_my_orders()
  File "/home/bitcoin/joinmarket-clientserver-0.6.0/jmvenv/lib/python3.7/site-packages/jmclient/yieldgenerator.py", line 82, in create_my_orders
    mix_balance = self.get_available_mixdepths()
  File "yg-acyclic.py", line 30, in get_available_mixdepths
    balances = self.wallet.get_balance_by_mixdepth(verbose=False)
builtins.AttributeError: 'YieldGeneratorAcyclic' object has no attribute 'wallet'

2019-12-02 00:00:33,215 [INFO]  starting yield generator
2019-12-02 00:00:33,401 [INFO]  Listening on port 27183
2019-12-02 00:00:33,402 [INFO]  Starting transaction monitor in walletservice
2019-12-02 00:00:40,873 [INFO]  Could not connect to *ALL* servers yet, waiting up to 60 more seconds.
2019-12-02 00:00:55,920 [INFO]  All IRC servers connected, starting execution.
```

**Comment by AdamISZ** [comment]
Thanks for the report. Indeed this is a bug that needs fixing, sorry about that; you'll have to use the standard scripts until it's fixed.

Will address soon (for other devs, in case it isn't obvious, this is related to the script not being updated for Joinmarket-clientserver issue 359, should be a pretty easy fix).
